version: "3"

networks:
  gitea:
    driver: bridge

services:
  server:
    image: docker.gitea.com/gitea:1.23.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__webhook__ALLOWED_HOST_LIST=jenkins,localhost
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    networks:
      - gitea
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home  # دیتا توی ./jenkins-data ذخیره می‌شه
      #- /var/run/docker.sock:/var/run/docker.sock  # این خط رو اضافه کنید
      #- ~/jenkins-kube:/var/jenkins_home/.kube
    depends_on:
      - db
    environment:
      - GIT_URL=http://gitea:3000/gitea/golang.git
      - DOCKER_HOST=tcp://host.docker.internal:2375
      
      
  localstack:
    image: localstack/localstack
    container_name: localstack_main
    ports:
      - "4566:4566"  # برای اتصال به LocalStack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  registry:
    image: registry:2
    container_name: local_registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./registry:/var/lib/registry
